[versions]
ktor = "3.0.1"

[libraries]

ktor-server-core         = { module = "io.ktor:ktor-server-core", version.ref="ktor" }
ktor-server-netty        = { module = "io.ktor:ktor-server-netty", version.ref="ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref="ktor" }

ktor-server-velocity = { module = "io.ktor:ktor-server-velocity", version.ref = "ktor" }
ktor-server-freemarker = { module = "io.ktor:ktor-server-freemarker", version.ref = "ktor" }
ktor-server-thymeleaf = { module = "io.ktor:ktor-server-thymeleaf", version.ref = "ktor" }

ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref="ktor" }

ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref="ktor" }

[bundles]
ktor-server = [
    "ktor-server-core", "ktor-server-netty", "ktor-server-status-pages",
    "ktor-server-content-negotiation",
    "ktor-server-freemarker", "ktor-server-velocity", "ktor-server-thymeleaf"
]

ktor-serialization = [
    "ktor-serialization-jackson"
]